apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-arbiter
  namespace: mongodb-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-arbiter
  template:
    metadata:
      labels:
        app: mongodb-arbiter
    spec:
      containers:
      - name: mongodb-arbiter
        image: mongo
        command: ["mongod", "--replSet", "rs0", "--port", "27017", "--bind_ip_all", "--oplogSize", "128"]
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"