// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: echo/echo.proto

package echo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EchoServiceClient is the client API for EchoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EchoServiceClient interface {
	SimpleEcho(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	ServerSideStreamEcho(ctx context.Context, in *EchoRequestWithCount, opts ...grpc.CallOption) (EchoService_ServerSideStreamEchoClient, error)
	ClientSideStreamEcho(ctx context.Context, opts ...grpc.CallOption) (EchoService_ClientSideStreamEchoClient, error)
}

type echoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEchoServiceClient(cc grpc.ClientConnInterface) EchoServiceClient {
	return &echoServiceClient{cc}
}

func (c *echoServiceClient) SimpleEcho(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, "/EchoService/SimpleEcho", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoServiceClient) ServerSideStreamEcho(ctx context.Context, in *EchoRequestWithCount, opts ...grpc.CallOption) (EchoService_ServerSideStreamEchoClient, error) {
	stream, err := c.cc.NewStream(ctx, &EchoService_ServiceDesc.Streams[0], "/EchoService/ServerSideStreamEcho", opts...)
	if err != nil {
		return nil, err
	}
	x := &echoServiceServerSideStreamEchoClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EchoService_ServerSideStreamEchoClient interface {
	Recv() (*EchoResponse, error)
	grpc.ClientStream
}

type echoServiceServerSideStreamEchoClient struct {
	grpc.ClientStream
}

func (x *echoServiceServerSideStreamEchoClient) Recv() (*EchoResponse, error) {
	m := new(EchoResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *echoServiceClient) ClientSideStreamEcho(ctx context.Context, opts ...grpc.CallOption) (EchoService_ClientSideStreamEchoClient, error) {
	stream, err := c.cc.NewStream(ctx, &EchoService_ServiceDesc.Streams[1], "/EchoService/ClientSideStreamEcho", opts...)
	if err != nil {
		return nil, err
	}
	x := &echoServiceClientSideStreamEchoClient{stream}
	return x, nil
}

type EchoService_ClientSideStreamEchoClient interface {
	Send(*EchoRequest) error
	CloseAndRecv() (*EchoResponse, error)
	grpc.ClientStream
}

type echoServiceClientSideStreamEchoClient struct {
	grpc.ClientStream
}

func (x *echoServiceClientSideStreamEchoClient) Send(m *EchoRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *echoServiceClientSideStreamEchoClient) CloseAndRecv() (*EchoResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(EchoResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EchoServiceServer is the server API for EchoService service.
// All implementations must embed UnimplementedEchoServiceServer
// for forward compatibility
type EchoServiceServer interface {
	SimpleEcho(context.Context, *EchoRequest) (*EchoResponse, error)
	ServerSideStreamEcho(*EchoRequestWithCount, EchoService_ServerSideStreamEchoServer) error
	ClientSideStreamEcho(EchoService_ClientSideStreamEchoServer) error
	mustEmbedUnimplementedEchoServiceServer()
}

// UnimplementedEchoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEchoServiceServer struct {
}

func (UnimplementedEchoServiceServer) SimpleEcho(context.Context, *EchoRequest) (*EchoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SimpleEcho not implemented")
}
func (UnimplementedEchoServiceServer) ServerSideStreamEcho(*EchoRequestWithCount, EchoService_ServerSideStreamEchoServer) error {
	return status.Errorf(codes.Unimplemented, "method ServerSideStreamEcho not implemented")
}
func (UnimplementedEchoServiceServer) ClientSideStreamEcho(EchoService_ClientSideStreamEchoServer) error {
	return status.Errorf(codes.Unimplemented, "method ClientSideStreamEcho not implemented")
}
func (UnimplementedEchoServiceServer) mustEmbedUnimplementedEchoServiceServer() {}

// UnsafeEchoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EchoServiceServer will
// result in compilation errors.
type UnsafeEchoServiceServer interface {
	mustEmbedUnimplementedEchoServiceServer()
}

func RegisterEchoServiceServer(s grpc.ServiceRegistrar, srv EchoServiceServer) {
	s.RegisterService(&EchoService_ServiceDesc, srv)
}

func _EchoService_SimpleEcho_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServiceServer).SimpleEcho(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EchoService/SimpleEcho",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServiceServer).SimpleEcho(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EchoService_ServerSideStreamEcho_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EchoRequestWithCount)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EchoServiceServer).ServerSideStreamEcho(m, &echoServiceServerSideStreamEchoServer{stream})
}

type EchoService_ServerSideStreamEchoServer interface {
	Send(*EchoResponse) error
	grpc.ServerStream
}

type echoServiceServerSideStreamEchoServer struct {
	grpc.ServerStream
}

func (x *echoServiceServerSideStreamEchoServer) Send(m *EchoResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _EchoService_ClientSideStreamEcho_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EchoServiceServer).ClientSideStreamEcho(&echoServiceClientSideStreamEchoServer{stream})
}

type EchoService_ClientSideStreamEchoServer interface {
	SendAndClose(*EchoResponse) error
	Recv() (*EchoRequest, error)
	grpc.ServerStream
}

type echoServiceClientSideStreamEchoServer struct {
	grpc.ServerStream
}

func (x *echoServiceClientSideStreamEchoServer) SendAndClose(m *EchoResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *echoServiceClientSideStreamEchoServer) Recv() (*EchoRequest, error) {
	m := new(EchoRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EchoService_ServiceDesc is the grpc.ServiceDesc for EchoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EchoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "EchoService",
	HandlerType: (*EchoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SimpleEcho",
			Handler:    _EchoService_SimpleEcho_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServerSideStreamEcho",
			Handler:       _EchoService_ServerSideStreamEcho_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ClientSideStreamEcho",
			Handler:       _EchoService_ClientSideStreamEcho_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "echo/echo.proto",
}
