apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-todo-app
  labels:
    app: todo-app
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "{{ .Values.service.port | quote }}"