apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-todo-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: todo-app
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 3000